### ISSUE TITLE
CommandLine reference missing

### ISSUE THREAD

**Issue by ArticuNode** [arxes-tolina/Tolina.StartAs#1]
Was just checking this out cos it looked interesting.. but have been unable to build, CommandLine is missing...

**Comment by fjakop** [comment]
How do you try to build it? Did you install nuget packages? 
The Travis-CI build is passing, so I can not see the problem (I've added a link in README.md)

**Comment by ArticuNode** [comment]
Apologies, it looks like I was having issues with nuget yesterday, its working fine now, thanks!
